DROP TABLE TBL_DETALLEMANTENIMIENTO CASCADE CONSTRAINTS;
DROP TABLE TBL_REGISTROMANTENIMIENTO CASCADE CONSTRAINTS;
DROP TABLE TBL_ACCIDENTE CASCADE CONSTRAINTS;
DROP TABLE TBL_COMBUSTIBLE CASCADE CONSTRAINTS;
DROP TABLE TBL_ASIGNACIONVEHICULO CASCADE CONSTRAINTS;
DROP TABLE TBL_MANTENIMIENTO CASCADE CONSTRAINTS;
DROP TABLE TBL_TIPOMANTENIMIENTO CASCADE CONSTRAINTS;
DROP TABLE TBL_VEHICULO CASCADE CONSTRAINTS;
DROP TABLE TBL_TIPO CASCADE CONSTRAINTS;
DROP TABLE TBL_MODELO CASCADE CONSTRAINTS;
DROP TABLE TBL_MARCA CASCADE CONSTRAINTS;
DROP TABLE TBL_ESTADO CASCADE CONSTRAINTS;
DROP TABLE TBL_USUARIO CASCADE CONSTRAINTS;
DROP TABLE TBL_ROL CASCADE CONSTRAINTS;
DROP TABLE TBL_TALLER CASCADE CONSTRAINTS;

CREATE TABLE TBL_ROL(
    ID_ROL INT GENERATED ALWAYS AS IDENTITY,
    NOMBREROL VARCHAR2(25) NOT NULL UNIQUE,
    CONSTRAINT PK_IDROL PRIMARY KEY(ID_ROL)
);
COMMENT ON COLUMN TBL_ROL.ID_ROL IS 'Identificador del rol.';
COMMENT ON COLUMN TBL_ROL.NOMBREROL IS 'Nombre del rol asignado, como Administrador o Motorista.';

CREATE TABLE TBL_USUARIO(
    ID_USUARIO INT GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CARNET VARCHAR2(15) NOT NULL UNIQUE,
    DUI VARCHAR2(10) CHECK(REGEXP_LIKE(DUI,'^[0-9]{8}-[0-9]{1}$')) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(9) CHECK(REGEXP_LIKE(TELEFONO,'^[0-9]{4}-[0-9]{4}$')) NOT NULL UNIQUE,
    CORREO VARCHAR2(50) CHECK(REGEXP_LIKE(CORREO,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')) NOT NULL UNIQUE,
    PASSWORDHASH VARCHAR2(255) NOT NULL,
    FK_ROL INT NOT NULL,
    CONSTRAINT PK_IDUSUARIO PRIMARY KEY(ID_USUARIO),
    CONSTRAINT FK_IDROL_ROL FOREIGN KEY(FK_ROL) REFERENCES TBL_ROL(ID_ROL)
);
COMMENT ON COLUMN TBL_USUARIO.ID_USUARIO IS 'Identificador del usuario.';
COMMENT ON COLUMN TBL_USUARIO.NOMBRE IS 'Nombres del empleado.';
COMMENT ON COLUMN TBL_USUARIO.APELLIDO IS 'Apellidos del empleado.';
COMMENT ON COLUMN TBL_USUARIO.CARNET IS 'Numero de carnet interno.';
COMMENT ON COLUMN TBL_USUARIO.DUI IS 'Documento de identidad del empleado sin guiones extras.';
COMMENT ON COLUMN TBL_USUARIO.TELEFONO IS 'Numero de telefono para contactarlo.';
COMMENT ON COLUMN TBL_USUARIO.CORREO IS 'Correo electronico corporativo o personal del empleado.';
COMMENT ON COLUMN TBL_USUARIO.PASSWORDHASH IS 'Contrasena guardada de forma segura para entrar al sistema.';
COMMENT ON COLUMN TBL_USUARIO.FK_ROL IS 'El rol que tiene este empleado en el sistema.';

CREATE TABLE TBL_ESTADO(
    ID_ESTADO INT GENERATED ALWAYS AS IDENTITY,
    NOMBREESTADO VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT PK_IDESTADO PRIMARY KEY(ID_ESTADO)
);
COMMENT ON COLUMN TBL_ESTADO.ID_ESTADO IS 'Identificador del estado.';
COMMENT ON COLUMN TBL_ESTADO.NOMBREESTADO IS 'Estado actual de un vehiculo, por ejemplo Disponible o En Taller.';

CREATE TABLE TBL_MARCA(
    ID_MARCA INT GENERATED ALWAYS AS IDENTITY,
    NOMBREMARCA VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT PK_IDMARCA PRIMARY KEY(ID_MARCA)
);
COMMENT ON COLUMN TBL_MARCA.ID_MARCA IS 'Identificador de la marca.';
COMMENT ON COLUMN TBL_MARCA.NOMBREMARCA IS 'Marca del fabricante del carro, como Toyota o Nissan.';

CREATE TABLE TBL_MODELO(
    ID_MODELO INT GENERATED ALWAYS AS IDENTITY,
    NOMBREMODELO VARCHAR2(50) NOT NULL,
    FK_MARCA INT NOT NULL,
    CONSTRAINT PK_IDMODELO PRIMARY KEY(ID_MODELO),
    CONSTRAINT UK_MODELO UNIQUE(NOMBREMODELO, FK_MARCA),
    CONSTRAINT FK_IDMARCA_MODELO FOREIGN KEY(FK_MARCA) REFERENCES TBL_MARCA(ID_MARCA)
);
COMMENT ON COLUMN TBL_MODELO.ID_MODELO IS 'Identificador del modelo.';
COMMENT ON COLUMN TBL_MODELO.NOMBREMODELO IS 'Nombre comercial del modelo del carro.';
COMMENT ON COLUMN TBL_MODELO.FK_MARCA IS 'Marca a la que pertenece este modelo de carro.';

CREATE TABLE TBL_TIPO(
    ID_TIPO INT GENERATED ALWAYS AS IDENTITY,
    NOMBRETIPO VARCHAR2(50) NOT NULL,
    FK_MODELO INT NOT NULL,
    CONSTRAINT PK_IDTIPO PRIMARY KEY(ID_TIPO),
    CONSTRAINT UK_TIPO UNIQUE(NOMBRETIPO, FK_MODELO),
    CONSTRAINT FK_IDMODELO_TIPO FOREIGN KEY(FK_MODELO) REFERENCES TBL_MODELO(ID_MODELO)
);
COMMENT ON COLUMN TBL_TIPO.ID_TIPO IS 'Identificador del tipo.';
COMMENT ON COLUMN TBL_TIPO.NOMBRETIPO IS 'Que tipo de vehiculo es, por ejemplo Sedan o Pick-up.';
COMMENT ON COLUMN TBL_TIPO.FK_MODELO IS 'Modelo exacto al que esta asociado este tipo.';

CREATE TABLE TBL_VEHICULO(
    ID_VEHICULO INT GENERATED ALWAYS AS IDENTITY,
    PLACA VARCHAR2(15) CHECK(REGEXP_LIKE(PLACA,'^[PCMNTR][1-9][0-9]{0,2}-[0-9]{1,3}$')) UNIQUE NOT NULL,
    KILOMETRAJE NUMBER(12,2) CHECK(KILOMETRAJE>=0) NOT NULL,
    NUMEROVIN VARCHAR2(17) NOT NULL UNIQUE CHECK(REGEXP_LIKE(NUMEROVIN,'^[A-HJ-NPR-Z0-9]{17}$')),
    TARJETACIRCULACION VARCHAR2(30) NOT NULL UNIQUE CHECK(REGEXP_LIKE(TARJETACIRCULACION,'^[A-Z0-9-]{5,30}$')),
    FK_TIPO INT NOT NULL,
    FK_ESTADO INT NOT NULL,
    CONSTRAINT PK_IDVEHICULO PRIMARY KEY(ID_VEHICULO),
    CONSTRAINT FK_IDTIPO_VEHICULO FOREIGN KEY(FK_TIPO) REFERENCES TBL_TIPO(ID_TIPO),
    CONSTRAINT FK_IDESTADO_ESTADO FOREIGN KEY(FK_ESTADO) REFERENCES TBL_ESTADO(ID_ESTADO)
);
COMMENT ON COLUMN TBL_VEHICULO.ID_VEHICULO IS 'Identificador del vehiculo en la flota.';
COMMENT ON COLUMN TBL_VEHICULO.PLACA IS 'Numero de placa asignado al vehiculo.';
COMMENT ON COLUMN TBL_VEHICULO.KILOMETRAJE IS 'Kilometraje actual que marca el tablero.';
COMMENT ON COLUMN TBL_VEHICULO.NUMEROVIN IS 'Numero de chasis del vehiculo.';
COMMENT ON COLUMN TBL_VEHICULO.TARJETACIRCULACION IS 'Numero de la tarjeta de circulacion.';
COMMENT ON COLUMN TBL_VEHICULO.FK_TIPO IS 'Clasificacion del vehiculo segun su tipo.';
COMMENT ON COLUMN TBL_VEHICULO.FK_ESTADO IS 'Situacion en la que se encuentra el carro hoy.';

CREATE TABLE TBL_ASIGNACIONVEHICULO(
    ID_ASIGNACION INT GENERATED ALWAYS AS IDENTITY,
    FK_USUARIO INT NOT NULL,
    FK_VEHICULO INT NOT NULL,
    FECHAASIGNACION DATE NOT NULL,
    HORASALIDA DATE,
    HORAENTREGA DATE,
    KILOMETRAJEINICIAL NUMBER(12,2),
    KILOMETRAJEFINAL NUMBER(12,2),
    OBSERVACIONES VARCHAR2(300),
    CONSTRAINT PK_IDASIGNACION PRIMARY KEY(ID_ASIGNACION),
    CONSTRAINT FK_IDUSUARIO_USUARIO FOREIGN KEY(FK_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO),
    CONSTRAINT FK_IDVEHICULO_ASIGNACION FOREIGN KEY(FK_VEHICULO) REFERENCES TBL_VEHICULO(ID_VEHICULO)
);
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.ID_ASIGNACION IS 'Identificador del viaje o asignacion.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.FK_USUARIO IS 'Motorista que va a manejar el carro.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.FK_VEHICULO IS 'Carro que se le esta entregando para salir.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.FECHAASIGNACION IS 'Fecha en la que se programo esta salida.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.HORASALIDA IS 'Fecha y hora exacta en la que el carro sale del predio.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.HORAENTREGA IS 'Fecha y hora exacta en la que regresan el carro.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.KILOMETRAJEINICIAL IS 'Kilometraje que marcaba el carro al arrancar.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.KILOMETRAJEFINAL IS 'Kilometraje que marcaba el carro al volver.';
COMMENT ON COLUMN TBL_ASIGNACIONVEHICULO.OBSERVACIONES IS 'Cualquier nota sobre como se entrego o como regreso el carro.';

CREATE TABLE TBL_ACCIDENTE(
    ID_ACCIDENTE INT GENERATED ALWAYS AS IDENTITY,
    FECHAACCIDENTE DATE NOT NULL,
    LUGAR VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    IMAGEN VARCHAR2(250),
    FK_ASIGNACION INT NOT NULL,
    CONSTRAINT PK_IDACCIDENTE PRIMARY KEY(ID_ACCIDENTE),
    CONSTRAINT FK_IDASIGNACION_ACCIDENTE FOREIGN KEY(FK_ASIGNACION) REFERENCES TBL_ASIGNACIONVEHICULO(ID_ASIGNACION)
);
COMMENT ON COLUMN TBL_ACCIDENTE.ID_ACCIDENTE IS 'Identificador del reporte de accidente.';
COMMENT ON COLUMN TBL_ACCIDENTE.FECHAACCIDENTE IS 'Fecha en la que ocurrio el percance en la calle.';
COMMENT ON COLUMN TBL_ACCIDENTE.LUGAR IS 'Direccion exacta donde paso el accidente.';
COMMENT ON COLUMN TBL_ACCIDENTE.DESCRIPCION IS 'Resumen de como fue el choque o el problema.';
COMMENT ON COLUMN TBL_ACCIDENTE.IMAGEN IS 'Foto de evidencia de los danos que recibio el carro.';
COMMENT ON COLUMN TBL_ACCIDENTE.FK_ASIGNACION IS 'Viaje en el que andaba el carro cuando paso el percance.';

CREATE TABLE TBL_COMBUSTIBLE(
    ID_COMBUSTIBLE INT GENERATED ALWAYS AS IDENTITY,
    GALONESTOTALES NUMBER(5,2) NOT NULL CHECK(GALONESTOTALES>0),
    FECHACARGA DATE DEFAULT SYSDATE NOT NULL,
    COSTO NUMBER(6,2) NOT NULL CHECK(COSTO>0),
    IMAGENFACTURA VARCHAR2(250) NOT NULL,
    FK_ASIGNACION INT NOT NULL,
    CONSTRAINT PK_IDCOMBUSTIBLE PRIMARY KEY(ID_COMBUSTIBLE),
    CONSTRAINT FK_IDASIGNACION_COMBUSTIBLE FOREIGN KEY(FK_ASIGNACION) REFERENCES TBL_ASIGNACIONVEHICULO(ID_ASIGNACION)
);
COMMENT ON COLUMN TBL_COMBUSTIBLE.ID_COMBUSTIBLE IS 'Identificador del gasto de combustible.';
COMMENT ON COLUMN TBL_COMBUSTIBLE.GALONESTOTALES IS 'Cuantos galones le echaron al carro en la gasolinera.';
COMMENT ON COLUMN TBL_COMBUSTIBLE.FECHACARGA IS 'Fecha en la que pasaron a repostar gasolina o diesel.';
COMMENT ON COLUMN TBL_COMBUSTIBLE.COSTO IS 'Cuanto costo la recarga en total de dinero.';
COMMENT ON COLUMN TBL_COMBUSTIBLE.IMAGENFACTURA IS 'Foto del ticket de compra de la gasolinera.';
COMMENT ON COLUMN TBL_COMBUSTIBLE.FK_ASIGNACION IS 'Viaje en el que se gasto este combustible.';

CREATE TABLE TBL_TALLER(
    ID_TALLER INT GENERATED ALWAYS AS IDENTITY,
    NOMBRETALLER VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(250) NOT NULL UNIQUE,
    RESPONSABLE VARCHAR2(100) NOT NULL,
    TELEFONOTALLER VARCHAR2(9) CHECK(REGEXP_LIKE(TELEFONOTALLER,'^[0-9]{4}-[0-9]{4}$')) NOT NULL UNIQUE,
    CONSTRAINT PK_IDTALLER PRIMARY KEY(ID_TALLER)
);
COMMENT ON COLUMN TBL_TALLER.ID_TALLER IS 'Identificador del taller mecanico externo.';
COMMENT ON COLUMN TBL_TALLER.NOMBRETALLER IS 'Nombre comercial del negocio o taller.';
COMMENT ON COLUMN TBL_TALLER.DIRECCION IS 'Direccion de adonde queda ubicado el taller.';
COMMENT ON COLUMN TBL_TALLER.RESPONSABLE IS 'Nombre del mecanico jefe o persona encargada del local.';
COMMENT ON COLUMN TBL_TALLER.TELEFONOTALLER IS 'Numero directo para llamar al mecanico del taller.';

CREATE TABLE TBL_TIPOMANTENIMIENTO(
    ID_TIPOMANTENIMIENTO INT GENERATED ALWAYS AS IDENTITY,
    NOMBRETIPOM VARCHAR2(25) NOT NULL CHECK(NOMBRETIPOM IN('Preventivo','Correctivo')),
    CONSTRAINT PK_IDTIPOMANTENIMIENTO PRIMARY KEY(ID_TIPOMANTENIMIENTO)
);
COMMENT ON COLUMN TBL_TIPOMANTENIMIENTO.ID_TIPOMANTENIMIENTO IS 'Identificador de la categoria del mantenimiento.';
COMMENT ON COLUMN TBL_TIPOMANTENIMIENTO.NOMBRETIPOM IS 'Indica si el mantenimiento es por rutina o para arreglar algo arruinado.';

CREATE TABLE TBL_MANTENIMIENTO(
    ID_MANTENIMIENTO INT GENERATED ALWAYS AS IDENTITY,
    NOMBREMANTENIMIENTO VARCHAR2(100) NOT NULL UNIQUE,
    COSTO NUMBER(10,2) NOT NULL CHECK(COSTO>=0),
    FK_TIPOMANTENIMIENTO INT NOT NULL,
    CONSTRAINT PK_IDMANTENIMIENTO PRIMARY KEY(ID_MANTENIMIENTO),
    CONSTRAINT FK_IDTIPOMANTENIMIENTO_TIPOM FOREIGN KEY(FK_TIPOMANTENIMIENTO) REFERENCES TBL_TIPOMANTENIMIENTO(ID_TIPOMANTENIMIENTO)
);
COMMENT ON COLUMN TBL_MANTENIMIENTO.ID_MANTENIMIENTO IS 'Identificador del servicio en el catalogo interno.';
COMMENT ON COLUMN TBL_MANTENIMIENTO.NOMBREMANTENIMIENTO IS 'Que trabajo exacto se va a hacer, como cambio de llantas o aceite.';
COMMENT ON COLUMN TBL_MANTENIMIENTO.COSTO IS 'Precio que suele cobrarse por este trabajo especificamente.';
COMMENT ON COLUMN TBL_MANTENIMIENTO.FK_TIPOMANTENIMIENTO IS 'A que categoria pertenece este trabajo de taller.';

CREATE TABLE TBL_REGISTROMANTENIMIENTO(
    ID_REGISTROMANTENIMIENTO INT GENERATED ALWAYS AS IDENTITY,
    FECHAENTRADA DATE NOT NULL,
    FECHASALIDA DATE,
    OBSERVACIONES VARCHAR2(500),
    FK_VEHICULO INT NOT NULL,
    FK_TALLER INT NOT NULL,
    FK_ACCIDENTE INT,
    CONSTRAINT PK_IDREGISTROMANTENIMIENTO PRIMARY KEY(ID_REGISTROMANTENIMIENTO),
    CONSTRAINT FK_IDVEHICULO_REGISTRO FOREIGN KEY(FK_VEHICULO) REFERENCES TBL_VEHICULO(ID_VEHICULO),
    CONSTRAINT FK_IDTALLER_TALLER FOREIGN KEY(FK_TALLER) REFERENCES TBL_TALLER(ID_TALLER),
    CONSTRAINT FK_IDACCIDENTE_ACCIDENTE FOREIGN KEY(FK_ACCIDENTE) REFERENCES TBL_ACCIDENTE(ID_ACCIDENTE) ON DELETE SET NULL
);
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.ID_REGISTROMANTENIMIENTO IS 'Identificador del ingreso del carro al mecanico.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.FECHAENTRADA IS 'Fecha en la que dejaron el vehiculo parqueado en el taller.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.FECHASALIDA IS 'Fecha en la que fueron a traer el vehiculo ya reparado.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.OBSERVACIONES IS 'Detalles extra sobre por que llevaron el carro o recomendaciones del taller.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.FK_VEHICULO IS 'Cual carro de la flota estan reparando.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.FK_TALLER IS 'A que taller mandaron el carro esta vez.';
COMMENT ON COLUMN TBL_REGISTROMANTENIMIENTO.FK_ACCIDENTE IS 'Reporte del choque, solo en caso de que lo esten arreglando por esa razon.';

CREATE TABLE TBL_DETALLEMANTENIMIENTO(
    ID_DETALLEMANTENIMIENTO INT GENERATED ALWAYS AS IDENTITY,
    CANTIDAD NUMBER(5) DEFAULT 1 NOT NULL CHECK(CANTIDAD>0),
    COSTO NUMBER(10,2) NOT NULL CHECK(COSTO>=0),
    FK_REGISTROMANTENIMIENTO INT NOT NULL,
    FK_MANTENIMIENTO INT NOT NULL,
    CONSTRAINT PK_IDDETALLEMANTENIMIENTO PRIMARY KEY(ID_DETALLEMANTENIMIENTO),
    CONSTRAINT FK_IDREGISTROMANTENIMIENTO_REGISTRO FOREIGN KEY(FK_REGISTROMANTENIMIENTO) REFERENCES TBL_REGISTROMANTENIMIENTO(ID_REGISTROMANTENIMIENTO),
    CONSTRAINT FK_IDMANTENIMIENTO_MANTENIMIENTO FOREIGN KEY(FK_MANTENIMIENTO) REFERENCES TBL_MANTENIMIENTO(ID_MANTENIMIENTO)
);
COMMENT ON COLUMN TBL_DETALLEMANTENIMIENTO.ID_DETALLEMANTENIMIENTO IS 'Identificador de la linea cobrada en la factura del taller.';
COMMENT ON COLUMN TBL_DETALLEMANTENIMIENTO.CANTIDAD IS 'Cuantas veces cobraron este servicio o cuantos repuestos le pusieron.';
COMMENT ON COLUMN TBL_DETALLEMANTENIMIENTO.COSTO IS 'Cuanto cobraron exactamente por este trabajo ya aplicado.';
COMMENT ON COLUMN TBL_DETALLEMANTENIMIENTO.FK_REGISTROMANTENIMIENTO IS 'Visita al taller donde hicieron este trabajo en el carro.';
COMMENT ON COLUMN TBL_DETALLEMANTENIMIENTO.FK_MANTENIMIENTO IS 'Trabajo del catalogo que estan cobrando en esta linea.';

CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHACARGA
BEFORE INSERT OR UPDATE ON TBL_COMBUSTIBLE
FOR EACH ROW
BEGIN
    IF :NEW.FECHACARGA > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'La fecha de carga no puede ser una fecha futura.');
    ELSIF :NEW.FECHACARGA < TRUNC(SYSDATE) - 30 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se pueden registrar facturas con mas de 30 dias de antiguedad.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHASALIDA
BEFORE INSERT OR UPDATE ON TBL_REGISTROMANTENIMIENTO
FOR EACH ROW
BEGIN
    IF :NEW.FECHASALIDA IS NOT NULL THEN
        IF :NEW.FECHASALIDA < :NEW.FECHAENTRADA THEN
            RAISE_APPLICATION_ERROR(-20002, 'La fecha de salida no puede ser menor que la fecha de entrada.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDAR_KILO_ASIGNACION
BEFORE INSERT OR UPDATE ON TBL_ASIGNACIONVEHICULO
FOR EACH ROW
BEGIN
    IF :NEW.KILOMETRAJEFINAL IS NOT NULL AND :NEW.KILOMETRAJEINICIAL IS NOT NULL THEN
        IF :NEW.KILOMETRAJEFINAL < :NEW.KILOMETRAJEINICIAL THEN
            RAISE_APPLICATION_ERROR(-20003, 'El kilometraje final no puede ser menor que el kilometraje inicial del viaje.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_KILOMETRAJE
AFTER INSERT OR UPDATE ON TBL_ASIGNACIONVEHICULO
FOR EACH ROW
DECLARE
    V_KM_ACTUAL NUMBER(12,2);
BEGIN
    IF :NEW.KILOMETRAJEFINAL IS NOT NULL THEN
        SELECT KILOMETRAJE INTO V_KM_ACTUAL
        FROM TBL_VEHICULO
        WHERE ID_VEHICULO = :NEW.FK_VEHICULO;

        IF :NEW.KILOMETRAJEFINAL > V_KM_ACTUAL THEN
            UPDATE TBL_VEHICULO
            SET KILOMETRAJE = :NEW.KILOMETRAJEFINAL
            WHERE ID_VEHICULO = :NEW.FK_VEHICULO;
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ESTADO_MANTENIMIENTO
AFTER INSERT OR UPDATE ON TBL_REGISTROMANTENIMIENTO
FOR EACH ROW
BEGIN
    IF :NEW.FECHASALIDA IS NULL THEN
        UPDATE TBL_VEHICULO
        SET FK_ESTADO = 2
        WHERE ID_VEHICULO = :NEW.FK_VEHICULO;
    ELSE
        UPDATE TBL_VEHICULO
        SET FK_ESTADO = 1
        WHERE ID_VEHICULO = :NEW.FK_VEHICULO;
    END IF;
END;
/
